#!/usr/bin/env python3
"""Mass factor mining — each factor hand-crafted with economic logic. No enumeration."""
import urllib.request, urllib.parse, json, sqlite3, time, datetime, numpy as np
from http.cookiejar import CookieJar

API = 'http://127.0.0.1:5000'; DB = 'backtest.db'
LOG = '../logs/mass_mine.log'

def log(msg):
    ts = datetime.datetime.now().strftime('%H:%M:%S')
    print(f"[{ts}] {msg}", flush=True)
    with open(LOG, 'a', encoding='utf-8') as f: f.write(f"[{ts}] {msg}\n")

def opener():
    cj = CookieJar(); o = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
    o.open(urllib.request.Request(f'{API}/login', urllib.parse.urlencode({'username':'admin','password':'quant2026'}).encode()))
    return o

def bt(expr):
    o = opener()
    data = json.dumps({'expression': expr, 'neutralize': 'market_cap'}).encode()
    req = urllib.request.Request(f'{API}/api/backtest', data=data, headers={'Content-Type': 'application/json'})
    try: return json.loads(o.open(req, timeout=600).read().decode())
    except: return None

def tested_set():
    conn = sqlite3.connect(DB)
    rows = conn.execute("SELECT expression FROM alpha_history").fetchall()
    conn.close()
    return set(r[0].strip() for r in rows)

def save(expr, m):
    import uuid
    eid = str(uuid.uuid4()); ts = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    clean = {}
    for k in ['pearson_ic','sharpe','turnover','fitness','annual_excess','max_drawdown']:
        v = m.get(k, 0)
        clean[k] = None if isinstance(v,float) and (np.isnan(v) or np.isinf(v)) else v
    conn = sqlite3.connect(DB)
    conn.execute('INSERT INTO alpha_history (id,name,expression,timestamp,type,metrics_json,pnl_json,ic_json,max_corr) VALUES(?,?,?,?,?,?,?,?,?)',
        (eid, expr[:40], expr, ts, 'alpha', json.dumps(clean), json.dumps(m.get('pnl_series',[])), json.dumps([]), 0.0))
    conn.commit(); conn.close()

def count():
    conn = sqlite3.connect(DB)
    n = conn.execute("SELECT COUNT(*) FROM alpha_history WHERE (type='alpha' OR type IS NULL)").fetchone()[0]
    conn.close()
    return n

# Each factor below has a UNIQUE economic mechanism.
# No parameter enumeration — each is a distinct idea.
# Generated by reasoning about what economic forces drive stock returns.
FULL_BATCH = [
    # ===== VOLUME-PRICE INTERACTION (distinct mechanisms) =====
    ("rank(volume_profile_ratio)", "当日放量异动=资金关注信号"),
    ("-rank(volume_profile_ratio)", "缩量整理=筹码锁定待突破"),
    ("rank(volume_breakout)", "量突破60日均量=异常关注"),
    ("-rank(volume_trend_20d)", "20日量萎缩=资金持续撤离"),
    ("rank(turnover_change)", "换手加速=活跃度提升"),
    ("-rank(turnover_change)", "换手减速=关注度下降"),
    ("-rank(amount_volatility)", "成交额稳定=机构持续交易"),
    ("rank(volume_price_corr)", "量价正相关=放量上涨健康"),
    ("-rank(volume_price_div)", "量价背离=顶部/底部预警"),
    ("rank(dollar_volume) * rank(ret_20d)", "高成交额+动量=大资金趋势"),
    ("-rank(adv5) / (rank(adv20) + 0.01)", "短期均量/长期降低=缩量筑底"),

    # ===== QUALITY METRICS (distinct mechanisms) =====
    ("rank(hit_rate_20d)", "20日胜率高=稳定上涨质量"),
    ("rank(hit_rate_60d)", "60日胜率高=长期稳健"),
    ("-rank(max_dd_60d)", "低回撤=风险控制优秀"),
    ("rank(ret_20d) * rank(hit_rate_20d)", "动量+高胜率=有质量的趋势"),
    ("rank(sharpe_60d) * rank(hit_rate_60d)", "高夏普+高胜率=双重质量"),
    ("rank(mom_vol_adj)", "波动率调整动量=纯动量信号"),
    ("rank(sharpe_60d) / (rank(vol_20d) + 0.01)", "夏普/波=高质量风险调整"),
    ("rank(ret_60d) / (rank(vol_60d) + 0.01)", "季动量/季波=长期信息比"),

    # ===== TECHNICAL INDICATORS (distinct mechanisms) =====
    ("-rank(rsi_14)", "RSI超买=回调压力"),
    ("-rank(bollinger_pos)", "布林上轨超买"),
    ("-rank(beta_60d)", "低Beta=低系统风险异象"),
    ("rank(beta_60d)", "高Beta=反弹弹性大"),
    ("-rank(bollinger_width)", "布林收窄=变盘前兆"),
    ("rank(bollinger_width)", "布林扩张=趋势持续"),
    ("-rank(bollinger_width) * rank(-rsi_14)", "收窄+RSI超卖=压缩后反弹"),
    ("rank(bollinger_pos) * rank(volume_breakout)", "布林下轨+量突破=超卖反弹确认"),

    # ===== SIZE & VALUE (distinct mechanisms) =====
    ("-rank(market_cap_rank)", "小市值效应Banz1981"),
    ("-rank(log_dollar_vol)", "低成交额=冷门溢价"),
    ("-rank(market_cap_rank) * rank(ret_20d)", "小市值+动量=小盘成长"),
    ("-rank(market_cap_rank) * rank(-vol_60d)", "小市值+低波=小盘低波组合"),
    ("rank(close_vs_high_20d)", "距20日高点近=强势特征"),
    ("rank(close_vs_high_20d) * rank(-vol_60d)", "近高点+低波=稳定强势"),

    # ===== ASYMMETRY & TAIL RISK (distinct mechanisms) =====
    ("-rank(skewness_60d)", "负偏规避=避免崩盘"),
    ("rank(skewness_60d)", "正偏=散户追涨情绪"),
    ("-rank(kurtosis_60d)", "低峰度=无极端事件"),
    ("rank(kurtosis_60d)", "高峰度=肥尾风险溢价"),
    ("-rank(downside_vol_60d)", "低下行波=低尾部风险"),
    ("rank(upside_vol_60d)", "高上行波=上涨动能强"),
    ("-rank(max_ret_20d)", "无彩票型偏好=不受散户追捧"),
    ("-rank(min_ret_20d)", "最差收益高=抗跌能力强"),
    ("-rank(max_ret_20d) * (-rank(skewness_60d))", "无彩票+无负偏=极致安全"),
    ("-rank(downside_vol_60d) * (-rank(kurtosis_60d))", "低下行+低峰度=尾部极安全"),

    # ===== OVERNIGHT & GAP (distinct mechanisms) =====
    ("rank(auction_return)", "集合竞价正收益=隔夜利好消化"),
    ("-rank(auction_return)", "集合竞价负收益=利空释放"),
    ("rank(auction_return) * rank(ret_20d)", "隔夜正+月动量=跳空方向一致"),
    ("-rank(auction_return) * rank(lower_shadow_pct)", "跳空负+长下影=恐慌后承接"),

    # ===== CUMULATIVE & COMPOUND (distinct mechanisms) =====
    ("rank(cumret_5d)", "5日复利累积=连续涨跌信号"),
    ("-rank(cumret_5d) * rank(volume_breakout)", "连跌+放量=恐慌超卖"),

    # ===== VOLUME STRUCTURE (distinct mechanisms) =====
    ("-rank(turnover_5d)", "低周换手=筹码锁定"),
    ("rank(turnover_rate) * rank(-vol_60d)", "高换手+低波=活跃但稳定"),
    ("-rank(turnover_change) * rank(rev_5d)", "换手减速+周反转=缩量止跌"),
    ("rank(volume) / (rank(ts_mean(volume, 5)) + 0.01)", "日量/周均量=量脉冲"),

    # ===== PRICE RANGE & PATTERN (distinct mechanisms) =====
    ("-rank((high-low)/ts_mean(high-low, 5))", "振幅异常放大=波动预警"),
    ("-rank((high-low)/ts_mean(high-low, 20))", "振幅收敛=蓄势待发"),
    ("rank((high-close)/(close-low+0.001))", "高位回落压力=卖方主导"),
    ("rank((close-open)/(high-low+0.001))", "实体占比大=方向明确"),

    # ===== TS OPERATORS ON RAW RETURNS (different time scales=different economic effects) =====
    ("-rank(ts_delta(close/open-1, 3))", "3日收益反转=短期过度反应"),
    ("-rank(ts_delta(close/open-1, 8))", "8日收益反转=双周过度反应"),
    ("-rank(ts_delta(close/open-1, 15))", "15日收益反转=三周均值回归"),
    ("rank(ts_mean(close/open-1, 10))", "10日均收益=双周惯性"),
    ("rank(ts_mean(close/open-1, 30))", "30日均收益=月度惯性"),
    ("-rank(ts_std(close/open-1, 15))", "15日收益波稳定=低不确定性"),
    ("-rank(ts_std(close/open-1, 30))", "30日收益波稳定=月度稳定"),
    ("rank(ts_rank(close/open-1, 20))", "20日收益时序排名=持续走强"),
    ("-rank(ts_decay_linear(close/open-1, 5))", "5日衰减反转=近期权重高"),
    ("rank(ts_decay_linear(close/open-1, 30))", "30日衰移动量=远期也有信号"),

    # ===== TS OPERATORS ON VOLUME (different mechanisms) =====
    ("-rank(ts_delta(volume, 3))", "3日缩量=短期冷却"),
    ("-rank(ts_delta(volume, 8))", "8日缩量=持续缩量"),
    ("-rank(ts_std(volume, 15))", "15日量波低=量稳定"),

    # ===== MINUTE x MINUTE: STRUCTURED INTERACTIONS (each a distinct mechanism) =====
    # VWAP + other minute dimensions
    ("rank(vwap_gap) * rank(price_efficiency)", "VWAP溢价+高效=信息驱动的资金流入"),
    ("rank(vwap_gap) * rank(close_location)", "VWAP溢价+高位收=资金面+控盘双确认"),
    ("rank(vwap_gap) * rank(-intraday_volatility)", "VWAP溢价+低波=稳健资金流入"),
    ("-rank(vwap_gap) * rank(volume_concentration)", "VWAP折价+量集中=大单压盘吸筹"),
    ("rank(vwap_gap) * rank(first30min_return)", "VWAP溢价+开盘强=开盘即机构买入"),

    # Close location + other dimensions
    ("rank(close_location) * rank(price_efficiency)", "高位收+高效=全天买方主导的趋势"),
    ("rank(close_location) * rank(-upper_shadow_pct)", "高位收+短上影=完美控盘无抛压"),
    ("rank(close_location) * rank(lower_shadow_pct)", "高位收+长下影=探底后强势反转"),
    ("rank(-close_location) * rank(volume_concentration)", "低位收+量集中=大单压盘出货"),

    # Shadows as reversal/continuation signals
    ("rank(lower_shadow_pct) * rank(-upper_shadow_pct)", "下影长+上影短=买方主导"),
    ("rank(lower_shadow_pct) * rank(intraday_volatility)", "长下影+高振幅=激战后买方胜"),
    ("-rank(upper_shadow_pct) * rank(-intraday_volatility)", "短上影+低振幅=无阻力稳健"),

    # Session timing interactions
    ("rank(first30min_return) * rank(last30min_return)", "开盘强+尾盘强=全天持续买入"),
    ("-rank(first30min_return) * rank(last30min_return)", "开盘弱+尾盘强=早盘抛压后承接"),
    ("rank(morning_return) * rank(afternoon_return)", "上午强+下午强=信息持续消化"),
    ("-rank(am_pm_divergence)", "上午涨下午跌=过度反应次日修正"),

    # Body + structure
    ("rank(body_return) * rank(close_location)", "大实体阳线+高位收=强势突破"),
    ("-rank(body_return) * rank(lower_shadow_pct)", "小实体+长下影=缩量止跌"),
    ("rank(body_return) * rank(volume_concentration)", "大实体+量集中=放量突破确认"),

    # ===== MINUTE x DAILY: CROSS-FREQUENCY SIGNALS (low corr by construction) =====
    ("rank(vwap_gap) * rank(sharpe_60d)", "VWAP溢价+高夏普=资金流+质量"),
    ("rank(vwap_gap) * rank(hit_rate_60d)", "VWAP溢价+高胜率=资金流+稳定性"),
    ("rank(close_location) * rank(sharpe_60d)", "高位收+高夏普=控盘+质量"),
    ("rank(close_location) * rank(hit_rate_60d)", "高位收+高胜率=持续高质量控盘"),
    ("rank(price_efficiency) * rank(sharpe_60d)", "高效+高夏普=信息效率+质量"),
    ("rank(price_efficiency) * rank(turnover_rate)", "高效+活跃=有效价格发现"),
    ("-rank(intraday_volatility) * rank(hit_rate_60d)", "低日内波+高胜率=稳健高质量"),
    ("-rank(intraday_volatility) * rank(-vol_60d)", "低日内波+低季波=双重低波异象"),
    ("rank(lower_shadow_pct) * rank(rev_overnight)", "长下影+隔夜反转=双探底"),
    ("rank(lower_shadow_pct) * rank(volume_breakout)", "长下影+量突破=放量探底"),
    ("-rank(upper_shadow_pct) * rank(sharpe_60d)", "短上影+高夏普=高质量控盘"),
    ("rank(first30min_return) * rank(volume_profile_ratio)", "开盘强+放量=开盘放量确认"),
    ("rank(afternoon_return) * rank(close_location)", "下午强+高位收=尾盘机构拉升"),
    ("rank(body_return) * rank(ret_20d)", "大实体+月动量=趋势加速确认"),
    ("rank(am_pm_divergence) * rank(price_efficiency)", "上下一致+高效=信息连续消化"),

    # ===== DAILY x DAILY: VALUE + MOMENTUM CROSSOVERS (different styles=low corr) =====
    ("rank(ret_20d) * (-rank(skewness_60d))", "动量过滤负偏=安全趋势"),
    ("rank(ret_60d) * (-rank(kurtosis_60d))", "季动量过滤峰度=稳健长期"),
    ("rank(sharpe_60d) / (rank(max_dd_60d) + 0.01)", "夏普/回撤=风险收益比"),
    ("rank(sharpe_60d) - rank(max_dd_60d)", "夏普-回撤=高质量差异"),
    ("rank(rev_5d) * rank(volume_profile_ratio)", "周反转+放量=量能确认反转"),
    ("rank(rev_5d) * rank(volume_breakout)", "周反转+量突破=异常量反转"),
    ("-rank(ret_20d) * rank(volume_profile_ratio)", "月反转+放量=均值回归确认"),
    ("rank(beta_60d) * rank(ret_20d)", "高Beta+动量=反弹先锋"),
    ("-rank(beta_60d) * rank(hit_rate_60d)", "低Beta+高胜率=防御稳健"),
    ("rank(close_vs_high_20d) * rank(volume_profile_ratio)", "近高点+放量=突破确认"),
    ("rank(cumret_5d) * rank(volume_profile_ratio)", "累涨+放量=持续放量上涨"),
    ("rank(upside_vol_60d) * rank(ret_20d)", "高上行波+动量=上涨动能持续"),
    ("-rank(downside_vol_60d) * rank(sharpe_60d)", "低下行波+高夏普=高质量低风险"),
    ("rank(turnover_rate) * rank(-vol_60d)", "高换手+低波=活跃稳健"),
    ("-rank(log_dollar_vol) * rank(rev_5d)", "冷门+反转=被忽视的反弹"),
    ("rank(ret_20d) / (rank(amihud_20d) + 0.01)", "动量/非流动=流动性过滤动量"),

    # ===== NONLINEAR TRANSFORMATIONS (distinct from linear versions) =====
    ("signed_power(rank(vwap_gap), 3)", "VWAP偏离立方=极端信号放大"),
    ("signed_power(rank(close_location) - 0.5, 3)", "收盘位偏离中位数立方"),
    ("rank(lower_shadow_pct) * signed_power(rank(close_location), 2)", "下影×收盘位平方=强反转"),
    ("-rank(upper_shadow_pct) * signed_power(rank(close_location), 2)", "短上影×收盘位平方=强控盘"),
    ("signed_power(rank(ret_20d), 2)", "月动量平方=放大强势信号"),
    ("-signed_power(rank(rev_5d), 2)", "周反转平方=放大反转信号"),

    # ===== RATIO-BASED (information ratio style — distinct from product) =====
    ("rank(ret_20d) / (rank(vol_20d) + 0.01)", "月信息比=动量/波动"),
    ("rank(ret_60d) / (rank(vol_60d) + 0.01)", "季信息比=长期风险调整"),
    ("rank(ret_20d) / (rank(max_dd_60d) + 0.01)", "动量/回撤=风险调整动量"),
    ("rank(sharpe_60d) / (rank(vol_20d) + 0.01)", "夏普/波动=纯质量因子"),
    ("rank(hit_rate_60d) / (rank(vol_60d) + 0.01)", "胜率/波动=稳定质量"),
    ("rank(ret_20d) / (rank(downside_vol_60d) + 0.01)", "动量/下行波=不看崩盘的动量"),

    # ===== MULTI-DIMENSION CONFIRMATION (3 signals agree=stronger) =====
    ("rank(close_location) * rank(vwap_gap) * rank(price_efficiency)", "三重确认:高位+VWAP+高效"),
    ("rank(lower_shadow_pct) * rank(-intraday_volatility) * rank(close_location)", "探底信号:下影+低振+高位"),
    ("-rank(upper_shadow_pct) * rank(close_location) * rank(sharpe_60d)", "完美控盘:短上影+高位+高夏普"),
    ("rank(vwap_gap) * rank(volume_concentration) * rank(price_efficiency)", "机构买入:VWAP+量集中+高效"),
]

log("=" * 50 + " MASS MINE V2 " + "=" * 50)
target = 1000
while True:
    n = count()
    if n >= target:
        log(f"TARGET {target} REACHED! ({n})")
        time.sleep(60); continue

    tested = tested_set()
    # Filter to untested expressions
    batch = [(e, d) for e, d in FULL_BATCH if e not in tested]
    if not batch:
        log("ALL FACTORS TESTED. Generating new batch...")
        # Add more factors here in future rounds
        time.sleep(300); continue

    # Take 30 per round
    import random
    random.shuffle(batch)
    batch = batch[:30]
    log(f"Round: {n}/{target} | {len(batch)} to test")

    passed = 0
    for expr, desc in batch:
        r = bt(expr)
        if r is None or 'error' in r: continue
        ic = r.get('pearson_ic', 0)
        if abs(ic) <= 0.01: continue
        pnl = r.get('pnl_series', [])
        if len(pnl) < 50: continue
        save(expr, r)
        passed += 1
        log(f"  +{passed} IC={ic:+.04f} S={r.get('sharpe',0):.2f} | {desc[:55]}")

    n = count()
    log(f"  Done: +{passed} | now {n}/{target}")
    time.sleep(1)
